kind: pipeline
type: docker
name: default

steps:
- name: go-test
  image: golang:1.13
  secrets: ['battleaxe']
  commands:
  - echo $battleaxe
  - go build
  - go test -v

- name: ls
  image: alpine/git
  commands:
  - git checkout -b build-${DRONE_BUILD_NUMBER}
  - mkdir test
  - echo aaaa >> test/abc.txt
  - git add test/
  - git commit -m "adding stuff"
  - git push origin build-${DRONE_BUILD_NUMBER}
